# Site settings
title: Felipe Albuquerque
email: fa@cesar.org.br
url: https://felipedealbuquerque.github.io/
description: Web designer e Front-End developer com mais de dez anos de experiência em desenvolvimento de softwares, entre aplicações web, mobile e para Tv Digital.'
skills: "Front-End Engineer - Web Designer - Graphic Artist - Speaker and More"
meta_author: Albuquerque Felipe

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: Felipe

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Felipe Albuquerque
  location: Brazil
  social: Redes Sociais
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/felipedeolinda
  - title: linkedin
    url: http://www.linkedin.com/in/felipedealbuquerque/
  - title: instagram
    url: http://www.instagram.com/felipedeolinda/
  - title: github
    url: http://github.com/felipedealbuquerque

# Postal address (add as many lines as necessary)
address:
  - line: Recife, Pernambuco
#  - line: Beverly Hills, CA 90210

# Credits content
credits: 'site desenvolvido com Jekyll'

# Build settings
markdown: kramdown
permalink: pretty
