# Welcome to Jekyll!

# Website settings
title: "Felipe de Albuquerque"
description: "Front-End Engineer & Designer and jsdaybr organizer"
keywords: "Jack,Jalpc,blog,Jekyll,github,gh-pages"
baseurl: "/"
url: "http://www.jack003.com"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'Felipe'
  first_name: 'Felipe'
  last_name: 'Albuquerque'
  email: 'fa@cesar.org.br'
  facebook_username: ''
  github_username: 'felipedealbuquerque'
  avatar: 'static/img/landing/felipe.jpg'
  desc: 'Web designer e Front-End developer com mais de dez anos de experiência em desenvolvimento de softwares, entre aplicações web, mobile e para Tv Digital.'

# localization
languages:
  - locale: 'pt-br'
    flag: 'static/img/flags/Brazil.png'
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# donate
donate:
  wechat1: 'static/img/pay/w1.jpeg'
  wechat5: 'static/img/pay/w5.jpeg'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  name: jalpc
  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  id: UA-73784599-1

# growingIO
gio:
  id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
